# -*- coding: utf-8 -*-
"""food_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9wzWvdLnaKkwrZa8Mo2UHj5uk3bMjQs
"""

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten, Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import os

thedir = '/content/drive/MyDrive/Colab Notebooks/food recognition/images/train'
categories = [ name for name in os.listdir(thedir) if os.path.isdir(os.path.join(thedir, name)) ]

print(categories)

image_size = [224, 224]

train = '/content/drive/MyDrive/Colab Notebooks/food recognition/images/train'
test = '/content/drive/MyDrive/Colab Notebooks/food recognition/images/test'

vgg = VGG19(input_shape=image_size + [3], weights='imagenet', include_top=False)

for layer in vgg.layers:
  layer.trainable = False

folders = glob('/content/drive/MyDrive/Colab Notebooks/food recognition/images/train/*')
len(folders)

x = Flatten()(vgg.output)
prediction = Dense(len(folders), activation='softmax')(x)

model = Model(inputs=vgg.input, outputs=prediction)
model.summary()

model.compile(
    loss = 'categorical_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
)

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory(train, 
                                                 target_size = [224, 224], 
                                                 batch_size = 32, 
                                                 class_mode = 'categorical')
test_set = test_datagen.flow_from_directory(test, 
                                            target_size = [224, 224], 
                                            batch_size = 32, 
                                            class_mode = 'categorical')

r = model.fit_generator(
  training_set,
  validation_data=test_set,
  epochs=20,
  steps_per_epoch=len(training_set),
  validation_steps=len(test_set)
)

from tensorflow.keras.models import load_model

model.save('/content/drive/MyDrive/Colab Notebooks/food recognition/model_food_recognition_vgg19.h5')

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

m=load_model('/content/drive/MyDrive/Colab Notebooks/food recognition/model_food_recognition_vgg19.h5')

img=image.load_img('/content/drive/MyDrive/Colab Notebooks/food recognition/index.jpeg',target_size=(224,224))

x = image.img_to_array(img)

x=x/255
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

y_out = np.argmax(model.predict(img_data), axis=1)
y_out = categories[y_out[0]]
print(y_out)

